---
- name: Deploy gitconfig
  git_config:
    scope: global
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
  - name: user.name
    value: "{{ git_name }}"
  - name: user.email
    value: "{{ git_email }}"

- name: Deploy additional packages for development
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - tox
  - /usr/bin/virtualenv
  - strace
  become: yes

- name: Make directories for symlinks
  file:
    name: "{{ item.src }}"
    state: directory
  become: yes
  with_items: "{{ root_links }}"

- name: Make symlinks
  file:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    state: link
    force: yes
  become: yes
  with_items: "{{ root_links }}"
