---
- name: Deploy gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ lookup('env', 'HOME') }}/.gitconfig"

- name: Deploy additional packages for development
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - tox
  - /usr/bin/virtualenv
  become: yes

- name: Make directories for symlinks
  file:
    name: "{{ item.src }}"
    state: directory
  become: yes
  with_items: "{{ root_links }}"

- name: Make symlinks
  file:
    src: "{{ item.src }}"
    name: "{{ item.name }}"
    state: link
    force: yes
  become: yes
  with_items: "{{ root_links }}"
